events {
    worker_connections 1024;
    # Other event settings can be added here if needed
}

http {
    

    server {
        listen 6050 ssl;
        listen [::]:6050 ssl ipv6only=on;

        # SSL configuration
        ssl_certificate ./assets/cert.pem;
        ssl_certificate_key ./assets/key.pem;

        # Increase the maximum body size
        client_max_body_size 1000M;

        # Recommended SSL settings
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';
        ssl_prefer_server_ciphers on;

   

        location /stream {
            proxy_pass http://localhost:5463/stream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            # Disable buffering to support streaming
            proxy_buffering off;
            chunked_transfer_encoding on;

            # Increase timeout for long-lived connections
            proxy_send_timeout 86400;
            proxy_read_timeout 86400;
        }

        location /ai/dataloop.json {
            alias /Users/ludovithorvath/Desktop/Repos/pipeline-trigger-gradio/dataloop.json;
            add_header Access-Control-Allow-Origin *;
        }

        location /ai {
            proxy_pass http://localhost:8084/ai;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_buffering off;  
            proxy_read_timeout 86400;
        }

        location /start-stream {
            proxy_pass http://localhost:5463/start-stream;

            # Prevent Nginx from buffering request body
            proxy_request_buffering off;
            client_body_temp_path /tmp;
            
            # Preserve original request headers
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Enable HTTP/1.1 for streaming
            proxy_http_version 1.1;
            
            # Handle WebSockets and SSE (Server-Sent Events)
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "keep-alive";

            # Important: Disable buffering for real-time streaming support
            proxy_buffering off;
            proxy_cache_bypass $http_upgrade;
            
            # Ensure chunked transfer encoding for streamed responses
            chunked_transfer_encoding on;

            # Prevent FastAPI from closing connections too early
            proxy_send_timeout 86400;
            proxy_read_timeout 86400;

            # Increase buffer sizes to handle large streaming responses
            proxy_buffer_size 128k;
            proxy_buffers 8 256k;
            proxy_busy_buffers_size 256k;
        }



    }
}

